### ISSUE TITLE
Network Architecture

### ISSUE THREAD

**Issue by dingyan1478** [JunlinHan/CWR#1]
Thank you for your great work. This method has achieved good results in underwater image restoration. But can you provide some structure of the whole network? It's hard to understand your network architecture just by looking at the code. 
Thank you!

**Comment by JunlinHan** [comment]
Hi dingyan1478, thanks for your kind words on our work.
The page limit of IGARSS is 4 pages including references, thus, I didn't include enough details in.
Generator architecture is based on CycleGAN, which is a ResNet-based generator with 9 residual blocks.  Discriminaor is also identical to CycleGAN's discriminator, which is a patchGAN discrminator.
You may look at this link for more details: [CycleGAN's architecture](https://towardsdatascience.com/overview-of-cyclegan-architecture-and-training-afee31612a2f?gi=af313f49f46e) .
For the patchNCE loss, the encoder is the first half of the generator.  The projection head is a two-layer MLP.  You may look at this link for more details: [CUT](https://github.com/taesungp/contrastive-unpaired-translation)

**Comment by dingyan1478** [comment]
Thank you!
