### ISSUE TITLE
Questions about testing

### ISSUE THREAD

**Issue by dingyan1478** [JunlinHan/CWR#2]
In the testing phase, it is not possible to input pictures directly, and then call the model of the trained generator to test the result. But why in the test phase, you still need to input two images, including realA and realB, can you explain?
Maybe there is something wrong with my understanding. I hope you can give me your valuable opinions!

**Comment by JunlinHan** [comment]
You are correct. 
In the test phase, the input is two folders, testA and testB. In our case, A is raw underwater images while B is restored images. The model performs A->B.
This is a property inherited from CUT. Sometimes people want to visualize identical results. That is, if the input is B, what will happen if we send B to model(A->B). 
The simplest solution is to ignore this, and just put **one** image into testB, then the test code works.
Another solution is to change the code of visdom.

**Comment by dingyan1478** [comment]
I see. Thank you for your reply!
