### ISSUE TITLE
Enhanced dataset

### ISSUE THREAD

**Issue by dingyan1478** [JunlinHan/CWR#3]
I'm sorry to disturb you again. I wonder if it's convenient for you to publish the code of your enhanced dataset, or if you can send me a copy privately?

Thank you!

**Comment by JunlinHan** [comment]
Hi, the code for making the dataset ( restored reference images or Ground Truth) is written in Matlab. It requires the water attenuation parameters. The depth/distance parameters are assigned manually.  My code may not perform well if you don't have access to the water parameters. Let me know if it still helps, I'm willing to share it.

**Comment by dingyan1478** [comment]
Thank you!
