### ISSUE TITLE
  Is CWR related to contrastive learning?

### ISSUE THREAD

**Issue by zrt791521360** [JunlinHan/CWR#4]
Thanks for your solid work!
In your paper,"We propose CWR, which leverages contrastive learning to maximize the mutual information...".I could not find something about contrastive learning.Can you describe how you use contrastive learning ?Thanks.

**Comment by JunlinHan** [comment]
Hi,
Yes, it's related to contrastive learning, but unlike those for visual representation learning.
Contrastive is mainly about patches in this paper.  For instance, for a patch showing a coral reef of the generated restored image, we should be able to more strongly associate it to the same coral reef patch of the raw input underwater image other than the rest of the patches of the image. 
You may check Equation 6 and Equation 7 in table 1.
