### ISSUE TITLE
About pre_train model:

### ISSUE THREAD

**Issue by tianshunhan** [JunlinHan/CWR#5]
Hello, thank you for your wonderful sharing!

I would like to ask how to use the pre-train model. I installed the environment according to Environment.yml, but during the test, the system will report the following error:

RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579022034529/work/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /opt/conda/conda-bld/pytorch_1579022034529/work/caffe2/serialize/inline_container.cc:132)

I want to ask that what is your training environment?

**Comment by JunlinHan** [comment]
Hi,
The training environment is pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.2.

Could you please try: 
conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=X -c pytorch 
where X is your cuda version.
or:
pip install torch==1.6.0 torchvision==0.7.0
You may find this page useful: https://pytorch.org/get-started/previous-versions/
I'm really sorry that I didn't test the environment created from Environment.yml. I will try to update a valid one later.

**Comment by JunlinHan** [comment]
@hanson-eye 
Hi,
I have updated a new Environment.yml, please try it.
Sorry for the inconvenience.

**Comment by tianshunhan** [comment]
Thank you for your answer!

I have tried the new Environment.yml and the pre-train model is already available. Thanks again for your sharing!

**Comment by JunlinHan** [comment]
Glad it helps! The pre-trained model may not perform well in different water types, but feel free to try it.
