### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by dingyan1478** [JunlinHan/CWR#6]
Hi!
I'd like to know when your dataset will be released?

**Comment by JunlinHan** [comment]
Hi,
Sorry, it may take more time. There's an internal review due to the policy of CSIRO. I assume it will be released around June.

**Comment by dingyan1478** [comment]
well！
Thank you!

**Comment by JunlinHan** [comment]
@dingyan1478 
Hi, 
We have released the dataset, I will add more details later today.

**Comment by dingyan1478** [comment]
Thank you!发自我的华为手机-------- 原始邮件 --------发件人： JunlinHan ***@***.***>日期： 2021年6月1日周二 18:53收件人： JunlinHan/CWR ***@***.***>抄送： dingyan1478 ***@***.***>, Mention ***@***.***>主    题： Re: [JunlinHan/CWR] dataset (#6)
@dingyan1478
Hi,
We have released the dataset, I will add more details later today.
